name: Deploy from Astro via Deno
on:
  push:
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - uses: actions/cache@v3
        id: deno_cache
        env:
          cache-name: cache-deno
        with:
          path: |
            node_modules
            /home/runner/.cache/deno
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/deno.lock', '**/bun.lock') }}
      - name: Bun Install
        run: bun i
      - name: Build Astro from Bun
        run: bun run build
      - run: |
          mkdir ./dist/dist
          cp -r ./dist/client ./dist/dist/client
      - name: Deploy Astro Website
        uses: denoland/deployctl@v1
        with:
          project: "nanohanote"
          entrypoint: server/entry.mjs
          root: dist
